# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: postgres
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: kash

test:
  <<: *default
  database: dantos_test

# production:
#   #  primary:
#   <<: *default
#   database: <%= ENV['RDS_DB_NAME'] %>
#   username: postgres
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: 10.92.112.210
#   port: <%= ENV['RDS_PORT'] %>
#  primary_replica:
#    <<: *default
#    database: <%#= ENV['RDS_DB_NAME'] %>
#    username: postgres
#    password: <%#= ENV['RDS_PASSWORD'] %>
#    host: 10.92.112.227
#    port: <%#= ENV['RDS_PORT'] %>
#    replica: true
